version: '4.30.0'
services:
  sqlserver:
    container_name: gestao_vagas_sqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    environment:
      - SA_PASSWORD=12345
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express